---
sudo: required
dist: trusty

env:
  global:
    - FOXBMS_SETUP_REPO_URL=https://github.com/foxBMS/foxBMS-setup.git
    - FOXBMS_SETUP_REPO_NAME=foxBMS-setup
    - FOXBMS_BUILD_ENV_BASE_DOCKER_IMAGE=ubuntu:xenial
    - FOXBMS_BUILD_ENV_DOCKER_IMAGE=foxbms-buildenv
    - FOXBMS_BUILD_ENV_APT_DEPENDENCIES="python2.7 python-pip git gcc-arm-none-eabi gdb-arm-none-eabi doxygen graphviz"
    - FOXBMS_BUILD_ENV_PIP_DEPENDENCIES="bitstring numpy"

language: generic

services:
  - docker

install:
  - docker pull $FOXBMS_BUILD_ENV_BASE_DOCKER_IMAGE
  - docker run -it --name foxbms-buildenv-bootstrap-stage1 $FOXBMS_BUILD_ENV_BASE_DOCKER_IMAGE bash -c "apt update && apt -y install $FOXBMS_BUILD_ENV_APT_DEPENDENCIES"
  - docker commit foxbms-buildenv-bootstrap-stage1 $FOXBMS_BUILD_ENV_DOCKER_IMAGE
  - docker run -it --name foxbms-buildenv-bootstrap-stage2 foxbms-buildenv bash -c "pip install $FOXBMS_BUILD_ENV_PIP_DEPENDENCIES"
  - docker commit foxbms-buildenv-bootstrap-stage2 $FOXBMS_BUILD_ENV_DOCKER_IMAGE

before_script:
  - export FOXBMS_CURRENT_REPO_NAME=$(python -c "from __future__ import print_function; import os; print(os.environ['TRAVIS_REPO_SLUG'].split('/')[1], end='')")
  - git clone $FOXBMS_SETUP_REPO_URL $FOXBMS_SETUP_REPO_NAME
  - mkdir $FOXBMS_SETUP_REPO_NAME/$FOXBMS_CURRENT_REPO_NAME && rsync -a --exclude $FOXBMS_SETUP_REPO_NAME . $FOXBMS_SETUP_REPO_NAME/$FOXBMS_CURRENT_REPO_NAME
  - docker run -it -v $(pwd):/gitroot -w="/gitroot/$FOXBMS_SETUP_REPO_NAME" $FOXBMS_BUILD_ENV_DOCKER_IMAGE python bootstrap.py -dbd -sr $FOXBMS_CURRENT_REPO_NAME foxBMS-tools FreeRTOS hal

script:
  - docker run -it -v $(pwd)/$FOXBMS_SETUP_REPO_NAME:/gitroot -w="/gitroot" $FOXBMS_BUILD_ENV_DOCKER_IMAGE python build.py -p
...

